# ⬇︎ แนะนำให้ลบบรรทัด version: ออก (Compose V2 ไม่ใช้แล้ว)

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fglabel_sql
    env_file: .env            # ✅ ชี้ไปที่ .env เดิม
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1'"]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "${MSSQL_HOST_PORT}:1433"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fglabel_rabbit
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_HOST_PORT}:5672"
      - "${RABBITMQ_MAN_PORT}:15672"

  redis:
    image: redis:7.2
    container_name: fglabel_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: fglabel_api_gateway
    env_file: .env
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.0.86,49381;Database=TFCPILOT;User ID=dvl;Password=Pr0gr@mm1ng;TrustServerCertificate=Yes;
      - Rabbit__Host=rabbitmq
      - Redis__Configuration=redis:6379,defaultDatabase=0
      - ASPNETCORE_URLS=http://+:${API_PORT}         # ✅ ใช้ค่าจาก .env
    ports:
      - "${API_PORT}:${API_PORT}"

  worker:
    build:
      context: ./apps/worker-service
    container_name: fglabel_worker
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_started
      mssql:
        condition: service_healthy

  web-ui:
    build:
      context: ./apps/web-ui
    container_name: fglabel_web
    env_file: .env
    depends_on:
      api-gateway:
        condition: service_started
    environment:
      - VITE_API_BASE=http://localhost:${API_PORT}
    ports:
      - "${WEB_PORT}:80"

volumes:
  mssql_data:
  redis_data: