@startuml
!define RECTANGLE class
RECTANGLE WebUI
RECTANGLE ApiGateway
RECTANGLE WorkerService
database SQLServer
queue RabbitMQ
cloud Redis
cloud AzureAD
cloud Grafana

WebUI --> ApiGateway : REST/SignalR
ApiGateway --> SQLServer : Dapper
ApiGateway --> Redis : Cache
ApiGateway --> RabbitMQ : Publish
ApiGateway --> AzureAD : MSAL
WorkerService --> RabbitMQ : Consume
WorkerService --> SQLServer : Dapper
WorkerService --> Grafana : OpenTelemetry
@enduml 